version: '3.8'

services:
  postgres:
    container_name: postgres_football
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
      POSTGRES_DB: ${POSTGRES_DB:-football}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - football-network

  redis:
    container_name: redis_football
    image: redis:alpine
    ports:
      - '6379:6379'
    networks:
      - football-network

networks:
  football-network:
    driver: bridge

volumes:
  postgres_data:
